### ISSUE TITLE
Dangerous use of "common" test-common module

### ISSUE THREAD

**Issue by honza-kasik** [hal/manatoko#21]
`test-common` is too generic and might lead to cumulating `helpers` and `utilities` there which is in my opinion a bad practice. "Purpose-based" name would be in my opinion much more describing and would prevent discussed situation.

**Comment by hpehl** [comment]
I agree. 

Currently, the module only contains a JUnit extension and a JUnit annotation. What about renaming the maven artifact to `manatoko-junit` and the folder to `junit`?

**Comment by honza-kasik** [comment]
+1, IMHO much better, I wouldn't have anything against using `manatoko-junit` everywhere.
